// client/src/routes/Home.svelte
<script>
  import { invoices } from '../stores.js';
  import facade from '../facade.js';
  import Dashboard from '../components/Dashboard.svelte';
  import Invoices from '../components/Invoices.svelte';

  if(!$invoices.length) {
    facade.loadInvoices();
  }
</script>

<Dashboard></Dashboard>
<Invoices></Invoices>

// client-2/src/views/Home.vue
<template>
  <div>
    <Dashboard></Dashboard>
    
  </div>

</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import Dashboard from "@/components/Dashboard.vue"; // @ is an alias to /src
import Invoices from "@/components/Invoices.vue";

@Component({
  components: {
    Dashboard
  }
})
export default class Home extends Vue {}
</script>
