// client-2/src/components/Dashboard.vue
<template>
  <div>
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="panel panel-danger panel-colorful">
          <div class="panel-body text-center">
            <p class="text-uppercase mar-btm text-sm">Overdue Invoices</p>
            <i class="fas fa-file-invoice-dollar fa-5x"></i>
            <hr />
            <p class="h2 text-thin">$5200.05</p>
            <!-- <small><span class="text-semibold">7%</span> Higher than yesterday</small> -->
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="panel panel-success panel-colorful">
          <div class="panel-body text-center">
            <p class="text-uppercase mar-btm text-sm">Received YTD</p>
            <i class="fas fa-calculator fa-5x"></i>
            <hr />
            <p class="h2 text-thin">$10,126.88</p>
            <!-- <small><span class="text-semibold"><i class="fa fa-unlock-alt fa-fw"></i> 154</span> Unapproved comments</small> -->
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="panel panel-primary panel-colorful">
          <div class="panel-body text-center">
            <p class="text-uppercase mar-btm text-sm">Outstanding</p>
            <i class="fas fa-dollar-sign fa-5x"></i>
            <hr />
            <p class="h2 text-thin">$7600.00</p>
            <!-- <small><span class="text-semibold"><i class="fa fa-shopping-cart fa-fw"></i> 954</span> Sales in this month</small> -->
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="panel panel-info panel-colorful">
          <div class="panel-body text-center">
            <p class="text-uppercase mar-btm text-sm">Monthly Avg Invoiced</p>
            <i class="fas fa-calendar fa-5x"></i>
            <hr />
            <p class="h2 text-thin">$3500.00</p>
            <!-- <small><span class="text-semibold"><i class="fa fa-dollar fa-fw"></i> 22,675</span> Total Earning</small> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import { Component, Vue } from "vue-property-decorator";

  @Component
  export default class Dashboard extends Vue {}
</script>

<style>
.panel {
  box-shadow: 0 2px 0 rgba(0, 0, 0, 0.05);
  border-radius: 0.25rem;
  border: 0;
  margin-bottom: 24px;
}

.panel-dark.panel-colorful {
  background-color: #3b4146;
  border-color: #3b4146;
  color: #fff;
}

.panel-danger.panel-colorful {
  background-color: #f76c51;
  border-color: #f76c51;
  color: #fff;
}

.panel-primary.panel-colorful {
  background-color: #5fa2dd;
  border-color: #5fa2dd;
  color: #fff;
}

.panel-info.panel-colorful {
  background-color: #4ebcda;
  border-color: #4ebcda;
  color: #fff;
}

.panel-success.panel-colorful {
  background-color: #28a745;
  border-color: #28a745;
  color: #fff;
}

.panel-body {
  padding: 25px 20px;
}

.panel hr {
  border-color: rgba(0, 0, 0, 0.1);
}

.mar-btm {
  margin-bottom: 15px;
}

h2,
.h2 {
  font-size: 28px;
}

.small,
small {
  font-size: 85%;
}

.text-sm {
  font-size: 0.9em;
}

.text-thin {
  font-weight: 300;
}

.text-semibold {
  font-weight: 600;
}
</style>

// client/src/components/Dashboard.svelte
<div>
  <div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="panel panel-danger panel-colorful">
        <div class="panel-body text-center">
          <p class="text-uppercase mar-btm text-sm">Overdue Invoices</p>
          <i class="fas fa-file-invoice-dollar fa-5x"></i>
          <hr>
          <p class="h2 text-thin">$5200.05</p>
          <!-- <small><span class="text-semibold">7%</span> Higher than yesterday</small> -->
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="panel panel-success panel-colorful">
        <div class="panel-body text-center">
          <p class="text-uppercase mar-btm text-sm">Received YTD</p>
          <i class="fas fa-calculator fa-5x"></i>
          <hr>
          <p class="h2 text-thin">$10,126.88</p>
          <!-- <small><span class="text-semibold"><i class="fa fa-unlock-alt fa-fw"></i> 154</span> Unapproved comments</small> -->
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="panel panel-primary panel-colorful">
        <div class="panel-body text-center">
          <p class="text-uppercase mar-btm text-sm">Outstanding</p>
          <i class="fas fa-dollar-sign fa-5x"></i>
          <hr>
          <p class="h2 text-thin">$7600.00</p>
          <!-- <small><span class="text-semibold"><i class="fa fa-shopping-cart fa-fw"></i> 954</span> Sales in this month</small> -->
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="panel panel-info panel-colorful">
        <div class="panel-body text-center">
          <p class="text-uppercase mar-btm text-sm">Monthly Avg Invoiced</p>
          <i class="fas fa-calendar fa-5x"></i>
          <hr>
          <p class="h2 text-thin">$3500.00</p>
          <!-- <small><span class="text-semibold"><i class="fa fa-dollar fa-fw"></i> 22,675</span> Total Earning</small> -->
        </div>
      </div>
    </div>        
	</div>
</div>

<style>

.panel {
  box-shadow: 0 2px 0 rgba(0,0,0,0.05);
  border-radius: .25rem;
  border: 0;
  margin-bottom: 24px;
}

.panel-dark.panel-colorful {
  background-color: #3b4146;
  border-color: #3b4146;
  color: #fff;
}

.panel-danger.panel-colorful {
  background-color: #f76c51;
  border-color: #f76c51;
  color: #fff;
}

.panel-primary.panel-colorful {
  background-color: #5fa2dd;
  border-color: #5fa2dd;
  color: #fff;
}

.panel-info.panel-colorful {
  background-color: #4ebcda;
  border-color: #4ebcda;
  color: #fff;
}

.panel-success.panel-colorful {
  background-color: #28a745;
  border-color: #28a745;
  color: #fff;
}

.panel-body {
  padding: 25px 20px;
}

.panel hr {
  border-color: rgba(0,0,0,0.1);
}

.mar-btm {
  margin-bottom: 15px;
}

h2, .h2 {
  font-size: 28px;
}

.small, small {
  font-size: 85%;
}

.text-sm {
  font-size: .9em;
}

.text-thin {
  font-weight: 300;
}

.text-semibold {
  font-weight: 600;
}

</style>
